### ISSUE TITLE
cssToRNStyle returns an object with the same values as string

### ISSUE THREAD

**Issue by betoharres** [Sharcoux/rn-css#13]
Hello, thanks for making this library. I'm trying to use it instead of styled-components because of the `rem` support, but as I want to use it along with `react-native-elements` I have to implement some components using the `attrs` method, for example:
```
const Button = styled(RNButton).attrs({
  titleStyle: {
    padding: 10,
  },
})``;
```
problem is that to keep using the `rem` units here I'd have to make use of  `cssToRNStyle` function, but I just tested and the function is not returning the values as numbers but as strings for some reason. Using the example from the docs, my console.log outputs:
```
backgroundColor: "blue"
borderBottomWidth: "12px"
borderLeftWidth: "12px"
borderRightWidth: "12px"
borderTopWidth: "12px"
width: "2rem"
```
Is there something I'm doing it wrong? Thanks!

**Comment by Sharcoux** [comment]
Hey!

Sorry, for some reason I missed your issue.

I fixed the implementation of `cssToRNStyle`. You can update to version 1.3.1

Thanks for the feedback!
