### ISSUE TITLE
Issue with NextJS

### ISSUE THREAD

**Issue by Jawad-LiftOff** [Sharcoux/rn-css#14]
Hi, I am trying to use rn-css with a mono-repo using NextJS and React-Native. I get the below error while trying to run it on NextJS

Do you have a working example with NextJS or any SSR app? Could you please help me out with this?

```
Error: Cannot find module 'react-native'
Require stack:
- /app-path/node_modules/rn-css/dist/index.js
- /app-path/web/.next/server/pages/index.js
- /app-path/node_modules/next/dist/next-server/server/require.js
- /app-path/node_modules/next/dist/next-server/server/load-components.js
- /app-path/node_modules/next/dist/next-server/server/api-utils.js
- /app-path/node_modules/next/dist/next-server/server/next-server.js
- /app-path/node_modules/next/dist/server/next.js
- /app-path/node_modules/next/dist/server/lib/start-server.js
- /app-path/node_modules/next/dist/cli/next-dev.js
- /app-path/node_modules/next/dist/bin/next
```

My app structure looks something like below

```
- web
   - package.json(includes react-native-web)
- app
   - package.json(includes react-native)
- shared
   - package.json(includes rn-css)
   
```

**Comment by Sharcoux** [comment]
The structure of your project seems wrong. Can you confirm that your intention is to use a common code for the app and the web?

You can try to use [this tool](https://www.npmjs.com/package/create-rnweb) to create your React-Native + React-Native-Web if you want to study the classic structure.

Basically, what you are missing here is the instruction that will explain that import from `react-native` package should be made from `react-native-web` instead. In webpack, that would be done with this alias:

```json
{
  resolve: {
    alias: {
        'react-native$': 'react-native-web'
    }
  } 
}
```

This should be part od your webpack-config.js

**Comment by Jawad-LiftOff** [comment]
Thank you for the quick response @Sharcoux 
I found the fix. Had to include the package for transpile in next.config.js file as below.

`const withTM = require('next-transpile-modules')([
  'rn-css'
])`

This also causes build errors because of the regex I believe, so had to add the below in the babel.config.js file

`presets: [
      'next/babel',
      '@babel/preset-env', {
        'exclude': ['@babel/plugin-proposal-unicode-property-regex', '@babel/plugin-transform-unicode-regex']
      }
    ],`

**Comment by Jawad-LiftOff** [comment]
Great package though. Excited to use it. Makes life easy for creating a mono-repo for react web and native
