### ISSUE TITLE
Have you done any performance analysis?

### ISSUE THREAD

**Issue by siderakis** [Sharcoux/rn-css#15]
Great work, it seems very powerful.

Just wondering if there is a performance impact of using this pattern over the standard one.

**Comment by Sharcoux** [comment]
A bit. The extra features come with an extra cost. I noticed around 10% time increase in the calculation of the view to render. But to be honest, unless you mount thousands of elements at the same time, you should not perceive any difference.
If you notice a difference, feel free to report.
You can try it by using the benchmark tool from styled components. It's in their lib.

**Comment by siderakis** [comment]
Very cool thanks!
