### ISSUE TITLE
Property font-weight don't accept numbers ( type NSNumber cannot be converted to NSString )

### ISSUE THREAD

**Issue by ROG3R-DEV** [Sharcoux/rn-css#17]
I can't add numeric values for font-weight in Text type element.

I tried: font-weight: '500';  font-weight: 500;  ... not working...

font-weight: normal; font-weight: bold; ... works fine.

```typescript
const StyledText = styled.Text`
     font-weight: 500;
`;
```

Android:
<img src="https://i.imgur.com/SssinhK.png" />

Ios:
<img src="https://i.imgur.com/CqyJJ8Y.png" />

**Comment by Sharcoux** [comment]
Thanks for the feedback. Let me fix this quick. Apparently react-native accepts numbers but it wants it as a string and is not able to convert it itself... :man_facepalming:

**Comment by Sharcoux** [comment]
Ok, Fixed in version 1.5.1

Please note that according to your RN version and the values you might chose for font-weight, you can meet limitations on Android: https://github.com/facebook/react-native/issues/26193

Don't hesitate to report if you meet any issue.

**Comment by ROG3R-DEV** [comment]
thanks @Sharcoux  , very grateful for keeping this amazing project! I will test as soon as possible.

**Comment by Sharcoux** [comment]
You're welcome :wink:

**Comment by Sharcoux** [comment]
@ROG3R-DEV I'll let you close the topic once you confirmed that it was working as expected.

**Comment by ROG3R-DEV** [comment]
@Sharcoux  I tested it today and I can guarantee that everything works correctly now! thanks
