### ISSUE TITLE
Theme support

### ISSUE THREAD

**Issue by danielkv** [Sharcoux/rn-css#18]
First of all, great job with this package.

I have a running application that runs either on web and mobile, so my problem is been unable to just swtich the libs, because of the theme issue.

the biggest problem is the var name used "shared", that doesn't make sense as I know. I'm open to help make this right and type the theme correctly and find an easy way to switch betweenstyled-components/native and rn-css.

For now I'll not use this lib ONLY because of it! I'm sure many other had the some similar problem.

**Comment by Sharcoux** [comment]
Oh, I didn't think of that... I didn't use the theme provided by styled-components because of typescript issues. So basically you just need shared to be renamed "theme" right?

I named it shared because it can contain any value that must be shared between components not only theme values. Language for instance, user preferences, etc. But I could create a theme prop that references shared.theme.

**Comment by danielkv** [comment]
Actually, I think it should be only **theme** really. Because the styled component Provider, injects the prop theme, since my project is using a lot of it, it would be a pain in the as hunting those. 

*Styled-components* also provides the **useTheme()** hook, your lib also does it?

I didn't have a chance to read your code yet, but I'll try do it today. I'm actually very excited about it. For sure is something styled components should've think of.

**Comment by Sharcoux** [comment]
Ok @danielkv , please check the version 1.5.0 and tell me if it suits your needs and work as intended.

**Comment by Sharcoux** [comment]
@danielkv Please close the Issue once you checked that the new version is working as expected.

**Comment by danielkv** [comment]
I actually, did a little check. I see you added the useTheme hook, but I'm not sure when creating a styled component the prop theme would be injected

**Comment by Sharcoux** [comment]
Well... That's because I'm stupid... Let me fix that.

**Comment by Sharcoux** [comment]
Ok, check version 1.5.3. Thanks

**Comment by danielkv** [comment]
I think for now we have it! I'll try to figure it out how to inject the theme type. If I do I let you know
