### ISSUE TITLE
Add "css" to use within a property

### ISSUE THREAD

**Issue by fera765** [Sharcoux/rn-css#2]
RNCSS 
  
```
`${props` =>
    props.user &&
    `
      width: 120px;
      color: #fff;
      margin-left: 10px;
      font: normal 15px/17px 'Robotoo';
    `}
```

import styled, {css} from 'styled-components/native'

```
${props` =>
    props.user &&
   css  `
      width: 120px;
      color: #fff;
      margin-left: 10px;
      font: normal 15px/17px 'Robotoo';
    `}
```

with css import, in vscode of o auto complete

**Comment by Sharcoux** [comment]
I didn't understand, sorry. What is the feature?

**Comment by fera765** [comment]
https://styled-components.com/docs/api#css

**Comment by Sharcoux** [comment]
Sorry but I don't see the point:

```javascript
const complexMixin = props => `
  color: ${props.whiteColor ? 'white' : 'black'};
`

const StyledComp = styled.div`
  ${props => (props.complex ? complexMixin(props) : 'color: blue;')};
`
```

**Comment by fera765** [comment]
highlighting RNCSS syntax without adding {css}

![rncss](https://user-images.githubusercontent.com/35400150/89024149-08885c80-d2fb-11ea-9e3e-c955ab69532d.png)



highlighting styled-components syntax without adding {css}
![styled](https://user-images.githubusercontent.com/35400150/89024153-0920f300-d2fb-11ea-95be-25fc180c5f2b.png)



vscode extension doesn't work without adding additional {css}

**Comment by Sharcoux** [comment]
Does this work with your extension:

```javascript
String`
  width: 120px;
`
```
