### ISSUE TITLE
`auto` property in `margin` shorthand doesn't get applied

### ISSUE THREAD

**Issue by hyoretsu** [Sharcoux/rn-css#48]
Using `margin-left: auto` works, but `margin: 0 2vw 0 auto;` doesn't. Afaik, they should work the same.

**Comment by Sharcoux** [comment]
Ah, nice catch. I'm gonna check that.

**Comment by Sharcoux** [comment]
Top of your mind, do you think about any other similar property that can accept `auto`?

**Comment by Sharcoux** [comment]
Should be solved in 1.8.14

Please report if you meet any issue
