### ISSUE TITLE
`&:active` CSS selector

### ISSUE THREAD

**Issue by Akronae** [Sharcoux/rn-css#49]
Is it possible to use the `&:active` CSS selector?  
In order to do something like:  
```ts
const MyBtn = styled(Button)`
  &:active {
    background-color: blue;
  }
`
```

**Comment by Sharcoux** [comment]
Good idea. I'll add this.

**Comment by Sharcoux** [comment]
Done. You can test version 1.9.0. Tell me if you meet any issue.

**Comment by Sharcoux** [comment]
Ok. On version 1.9.1, we support `&:focus` **AND** `&:active`. This way you should be able to achieve your needs. Feel free to provide feedback.

**Comment by Sharcoux** [comment]
Will close as I'm successfully using it in my own project. Feel free to reopen if needed.
