### ISSUE TITLE
TS2349: This expression is not callable.   Type 'Element' has no call signatures.

### ISSUE THREAD

**Issue by sangayt1997** [Sharcoux/rn-css#50]
I have been developing the web and mobile app using expo but previous version use to be working but sudden updating to latest version of rn-css and It didn't work.

Paackage got following version: 
`
"rn-css": "^1.9.0",
"react": "18.2.0",
"react-native-web": "~0.18.12",
"native-base": "^3.4.28",
"react-native": "0.71.8",
"expo": "~48.0.16",
`

My code: 

`
import { Box } from 'native-base';
import styled from 'rn-css';

interface ContainerProps {
  backgroundColor?: string;
  height?: string;
}

const Container = styled(Box)`
  background-color: ${(props: ContainerProps) =>
          props.backgroundColor ||  '#e3e3e3'};
  height: ${(props: ContainerProps) => props.height || '100vh'}
`

export default SdContainer;

`

Your Help will be appreciated

**Comment by sangayt1997** [comment]
@Sharcoux I am wondering that it might be the example used in this repo packages.
<img width="703" alt="Screenshot 2023-06-13 at 16 28 04" src="https://github.com/Sharcoux/rn-css/assets/59992112/04e463ef-966c-4662-9819-d780f9ad094e">
Whenever use this package now i get this render

**Comment by Sharcoux** [comment]
Can you provide an example of how you are using the package? Maybe on [snack expo](https://snack.expo.dev/)?

**Comment by Sharcoux** [comment]
OMG, ok, that was my bad. I'm gonna fix right now.

**Comment by Sharcoux** [comment]
Fixed in v1.9.2. Sorry for the inconvenience.

**Comment by sangayt1997** [comment]
Thank you @Sharcoux for fixing it soon
