### ISSUE TITLE
Windows and Mac support

### ISSUE THREAD

**Issue by evanmoran** [Sharcoux/rn-css#7]
I really like the idea of this. Are you planning on supporting react native on windows and mac as well? I think that might fit well into the goal of css with hover states!

**Comment by Sharcoux** [comment]
Well, it should be working with windows and Mac out of the box as it is pure react-native. Did you encounter an issue?

**Comment by evanmoran** [comment]
No I didn’t. I’ll investigate and reopen if I find specific issues. Thanks!
