### ISSUE TITLE
A LICENSE file

### ISSUE THREAD

**Issue by evanmoran** [Sharcoux/rn-css#8]
It looks like you're missing a license file. Can you add one please to allow us to consider this for adoption? :)

**Comment by Sharcoux** [comment]
Oh, my bad then. I'll add it tomorrow. It will probably be sth like MIT license.

**Comment by Sharcoux** [comment]
It was actually licensed as ISC through the package.json. I added a copy of the license in the files.

**Comment by evanmoran** [comment]
Thank you!
